# ThbgmExtractor用外部エンコーダ設定ファイル
# 
# * 設定内容
# 
#   外部エンコーダを起動するための引数などを指定するためのファイルです。
#   外部エンコーダの設定をこのファイルに記入することで、メニュー項目の
#   エンコーダ一覧に表示されるようになります。
# 
#   書式は一般的なiniファイル形式と同様です。　'#'と';'で始まる行は
#   コメントとして扱われます。
# 
#   各キーの指定内容は次のとおりです。
# 
#   executable: [必須] エンコーダのexeファイル名またはフルパス。
#               exeファイルがThbgmExtractor.exeと同じフォルダに無い
#               場合はフルパスで指定してください。
# 
#   arguments:  [必須] エンコーダを起動する際に指定する引数。
#               入力・出力ファイルのパスは環境変数THBGM_INPUTFILEPATH
#               およびTHBGM_OUTPUTFILEPATHに設定されます(後述)。
#               標準入力を使用する場合は、入力ファイルの代わりに
#               '-'などを指定した上で、stdinにyesを指定してください。
# 
#   extension:  [必須] エンコード後のファイルの拡張子。
# 
#   stdin:      [オプション] 標準入力を経由してエンコードするかどうか。
#               エンコーダが標準入力からのエンコードに対応していて、
#               標準入力からのエンコードを使用する場合は、yesを指定して
#               ください。
#               stdinキーがない場合や、yes以外を指定した場合は標準入力を
#               使用しません。
# 
#   env[XXX]:   [オプション] エンコーダに渡す追加の環境変数(後述)。
# 
# 
#   エントリ名(かぎ括弧で囲まれた部分、'[***]')には任意の名称を指定して
#   ください。
#   この部分は一覧に表示される時の名前として使用されます。
# 
#   executableキーに指定するexeファイルにはエンコーダ以外も指定できます。
#   コマンドラインインターフェイスを備えている実行ファイルなら何でも
#   実行できるので、エンコード設定をラップしたバッチファイルや、音量調整・
#   波形編集などの加工を行うツールなどを起動することもできます。
# 
# 
# * 環境変数
# 
#   ThbgmExtractorは、外部エンコーダを起動する際に以下の環境変数を
#   設定します。
# 
#     THBGM_INPUTFILEPATH     入力ファイルのパス(Waveファイル)
#     THBGM_OUTPUTFILEPATH    出力ファイルのパス
# 
#   標準入力を使用する場合、THBGM_INPUTFILEPATHの値は設定されません。
# 
#   外部エンコーダを起動する際に上記以外の環境変数を設定したい場合は、
#   次の例のようにenv[XXX]を指定してください。
# 
#     executable  = encoder.exe
#     arguments   = ...
#     extension   = ...
#     env[PATH]   = E:\MyTools\bin;%PATH%
#     env[HOGE]   = piyo
# 
# 
# * 動作確認済みのエンコーダ
# 
#   下記のエンコーダでの動作を確認しています。
# 
#   Windows
#     FAAC 1.28 (http://www.rarewares.org/aac-encoders.php)
#     Oggenc 2.88 (http://www.rarewares.org/ogg-oggenc.php)
#     LAME 3.99.5 (http://www.rarewares.org/mp3-lame-bundle.php)
#   Linux
#     FFmpeg SVN-r20587 (svn://svn.ffmpeg.org/ffmpeg/trunk)
#     avconv 9.5 (http://libav.org/download.html)
# 
#   設定を書いてやりさえすれば、上記以外のコマンドライン型エンコーダでも
#   動作すると思います。
# 
# 
# * 記入例
# 
#   以下に記述されているエントリは記入例です。
#   コメントアウトしてあるのでエンコーダ一覧には表示されません。
#   該当するバージョンのexeファイルを用意し、行頭の"; "を削除すればすれば
#   そのままで使えます。
#

; [MPEG-4 AAC 128kbps / FAAC 1.28, pipe out]
; executable = faac.exe
; arguments  = -w -b 128 - -o "%THBGM_OUTPUTFILEPATH%"
; extension  = m4a
; stdin      = yes

; [Ogg Vorbis 192kbps / OggEnc 2.88, pipe out]
; executable = oggenc2.exe
; arguments  = -b 192 - -o "%THBGM_OUTPUTFILEPATH%"
; extension  = ogg
; stdin      = yes

; [MP3 192kbps / LAME 3.99.5, pipe out]
; executable = lame.exe
; arguments  = -h -b 192 --priority 3 - "%THBGM_OUTPUTFILEPATH%"
; extension  = mp3
; stdin      = yes

; [MPEG-4 AAC 128kbps / FFmpeg+libfaac(Linux), pipe out]
; executable = ffmpeg
; arguments  = -y -i - -acodec libfaac -ab 128k -f mp4 "$THBGM_OUTPUTFILEPATH"
; extension  = m4a
; stdin      = yes

#
# 以下の設定は標準入力を使用しない設定です。
# 上の設定でうまくいかない場合、代わりに以下の設定を試してみてください。
#

; [MPEG-4 AAC 128kbps / FAAC 1.28, file out]
; executable = faac.exe
; arguments  = -w -b 128 "%THBGM_INPUTFILEPATH%" -o "%THBGM_OUTPUTFILEPATH%"
; extension  = m4a
; stdin      = no

; [Ogg Vorbis 192kbps / OggEnc 2.88, file out]
; executable = oggenc2.exe
; arguments  = -b 192 "%THBGM_INPUTFILEPATH%" -o "%THBGM_OUTPUTFILEPATH%"
; extension  = ogg
; stdin      = no

; [MP3 192kbps / LAME 3.99.5, file out]
; executable = lame.exe
; arguments  = -h -b 192 --priority 3 "%THBGM_INPUTFILEPATH%" "%THBGM_OUTPUTFILEPATH%"
; extension  = mp3
; stdin      = no

; [MPEG-4 AAC 128kbps / FFmpeg+libfaac(Linux), file out]
; executable = ffmpeg
; arguments  = -y -i "$THBGM_INPUTFILEPATH" -acodec libfaac -ab 128k -f mp4 "$THBGM_OUTPUTFILEPATH"
; extension  = m4a
; stdin      = yes
